traefik:
  enabled: true
  namespaceOverride: traefik
  persistence:
    enabled: true
    path: /data
  additionalArguments:
    - "--certificatesresolvers.myresolver.acme.tlschallenge"
    - "--certificatesresolvers.myresolver.acme.email=mostafa@kotal.co"
    - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
  # The "volume-permissions" init container is required if you run into permission issues.
  # Related issue: https://github.com/traefik/traefik/issues/6825
  deployment:
    initContainers:
      - name: volume-permissions
        image: busybox:1.35
        command:
          - "sh"
          - "-c"
          - "touch /data/acme.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme.json"
        volumeMounts:
          - name: data
            mountPath: /data

cert-manager:
  enabled: true
  namespace: "cert-manager"
  installCRDs: true

postgresql:
  enabled: true
  auth:
    username: satoshi
    password: secret
    database: kotal
