apiVersion: v2
name: kotal
description: Kotal transforms your Kubernetes cluster into a powerful Node as a Service, Staking as a Service, and API gateway
type: application
version: 1.1.1
appVersion: "0.2.0"
dependencies:
  - name: "cert-manager"
    version: "1.13.0"
    repository: "https://charts.jetstack.io"
    condition: "cert-manager.enabled"
  - name: "traefik"
    version: "24.0.0"
    repository: "https://traefik.github.io/charts"
    condition: "traefik.enabled"
  - name: "postgresql"
    version: "12.11.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: "postgresql.enabled"
  - name: "metrics-server"
    version: "6.5.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: "metrics-server.enabled"
