apiVersion: v2
name: kotal
description: Kotal transforms your Kubernetes cluster into a powerful Node as a Service, Staking as a Service, and API gateway
type: application
version: 0.1.0-rc.1
appVersion: "0.1.0"
dependencies:
  - name: "cert-manager"
    version: "1.10.1"
    repository: "https://charts.jetstack.io"
    condition: "cert-manager.enabled"
  - name: "traefik"
    version: "20.5.3"
    repository: "https://traefik.github.io/charts"
    condition: "traefik.enabled"
  - name: "postgresql"
    version: "12.1.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: "postgresql.enabled"
