staging: false

api:
  tag: "v0.2.0"
  crossover_api_key: "c7f1f03dde5fc0cab9aa53081ed08ab797ff54e52e6ff4e9a38e3e092ffcf7c5"
  sendgrid_api_key: ""

dashboard:
  tag: "v0.2.0"

manager:
  tag: "v0.2.0"

metrics-server:
  enabled: true
  namespaceOverride: metrics-server
  extraArgs:
    - --kubelet-use-node-status-port
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
traefik:
  enabled: true
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  namespaceOverride: traefik
  persistence:
    enabled: true
    path: /data
  additionalArguments:
    - "--certificatesresolvers.myresolver.acme.tlschallenge"
    - "--certificatesresolvers.myresolver.acme.email=letsencrypt@kotal.co"
    - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
    - "--providers.kubernetescrd.allowCrossNamespace=true"
    - "--experimental.plugins.crossover.modulename=github.com/kotalco/crossover"
    - "--experimental.plugins.crossover.version=v0.1.7"

  # The "volume-permissions" init container is required if you run into permission issues.
  # Related issue: https://github.com/traefik/traefik/issues/6825
  # Enable experimental
  experimental:
    plugins:
      # -- Enable traefik experimental plugins
      enabled: false
  additionalVolumeMounts:
    - name: plugins
      mountPath: /plugins-storage
  deployment:
    initContainers:
      - name: volume-permissions
        image: busybox:1.35
        command:
          - "sh"
          - "-c"
          - "touch /data/acme.json && chown 65532:65532 /data/acme.json && chmod 600 /data/acme.json"
        securityContext:
          runAsGroup: 65532
          runAsUser: 65532
        volumeMounts:
          - name: data
            mountPath: /data
    additionalVolumes:
      - name: plugins
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"
  podSecurityContext:
    fsGroup: 65532

cert-manager:
  enabled: true
  namespace: "cert-manager"
  installCRDs: true
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"
  webhook:
    timeoutSeconds: 29
    resources:
      requests:
        cpu: "5m"
        memory: "25Mi"
  cainjector:
    resources:
      requests:
        cpu: "5m"
        memory: "25Mi"

postgresql:
  enabled: true
  primary:
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
  auth:
    username: satoshi
    password: "ecbf843e70d88b4d18912730f7a6ae03"
    database: kotal
