staging: false

api:
  tag: "v0.1.0"

dashboard:
  tag: "v0.1.0"

manager:
  tag: "v0.1.0"

traefik:
  enabled: true
  namespaceOverride: traefik
  persistence:
    enabled: true
    path: /data
  additionalArguments:
    - "--certificatesresolvers.myresolver.acme.tlschallenge"
    - "--certificatesresolvers.myresolver.acme.email=letsencrypt@kotal.co"
    - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
    - "--experimental.plugins.crossover.modulename=github.com/kotalco/crossover"
    - "--experimental.plugins.crossover.version=v0.1.2"
  # The "volume-permissions" init container is required if you run into permission issues.
  # Related issue: https://github.com/traefik/traefik/issues/6825
  deployment:
    initContainers:
      - name: volume-permissions
        image: busybox:1.35
        command:
          - "sh"
          - "-c"
          - "touch /data/acme.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme.json"
        volumeMounts:
          - name: data
            mountPath: /data
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"

cert-manager:
  enabled: true
  namespace: "cert-manager"
  installCRDs: true
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"
  webhook:
    timeoutSeconds: 30
    resources:
      requests:
        cpu: "5m"
        memory: "25Mi"
  cainjector:
    resources:
      requests:
        cpu: "5m"
        memory: "25Mi"

postgresql:
  enabled: true
  primary:
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
  auth:
    username: satoshi
    password: "ecbf843e70d88b4d18912730f7a6ae03"
    database: kotal
