---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: kotal
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "40"
spec:
  dnsNames:
    - webhook-service.kotal.svc
    - webhook-service.kotal.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
