apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kotal-api
rules:
  - apiGroups:
      - ethereum.kotal.io
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ethereum2.kotal.io
    resources:
      - beaconnodes
      - validators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ipfs.kotal.io
    resources:
      - peers
      - clusterpeers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - filecoin.kotal.io
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - chainlink.kotal.io
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - polkadot.kotal.io
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - near.kotal.io
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - namespaces
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - middlewares
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
