apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotal-api
spec:
  selector:
    matchLabels:
      app: kotal-api
  template:
    metadata:
      labels:
        app: kotal-api
    spec:
      serviceAccountName: kotal-api
      containers:
        - name: kotal-api
          image: kotalco/cloud-api:641bbd1
          env:
            - name: ENVIRONMENT
              value: production
            - name: DB_SERVER_URL
              value: "postgres://satoshi:secret@kotal-postgresql:5432/kotal"
            - name: SUBSCRIPTION_API_BASE_URL
              value: https://{{ if .Values.staging }}staging-{{ end }}subscriptions.kotal.co/api
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - containerPort: 6000
