apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotal-api
spec:
  selector:
    matchLabels:
      app: kotal-api
  template:
    metadata:
      labels:
        app: kotal-api
    spec:
      serviceAccountName: kotal-api
      containers:
        - name: kotal-api
          image: kotalco/core-api:{{ .Values.api.tag }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENVIRONMENT
              value: production
            - name: DB_SERVER_URL
              value: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@kotal-postgresql:5432/{{ .Values.postgresql.auth.database }}"
            - name: SUBSCRIPTION_API_BASE_URL
              value: https://{{ if .Values.staging }}staging-{{ end }}subscriptions.kotal.co
            - name: CROSSOVER_API_KEY
              value: "{{ .Values.api.crossover_api_key }}"
            - name: CROSSOVER_PATTERN
              value: "([a-z0-9]{42})"
            - name: CROSSOVER_REMOTE_ADDRESS
              value: "http://kotal-api.$(POD_NAMESPACE):6000/api/v1/crossover/endpoints/stats"
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - containerPort: 6000

