name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Add helm dependencies repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run chart-testing (lint)
        run: |
          ct lint --validate-maintainers=false --check-version-increment=false --target-branch main

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run chart-dependency-update
        run: helm dependency update charts/kotal

      - name: Upgrading traefik CRDs
        run: |
          kubectl apply --server-side --force-conflicts -k https://github.com/traefik/traefik-helm-chart/traefik/crds/

      - name: Run chart-testing (install)
        run: |
          helm install kotal charts/kotal --create-namespace --namespace=kotal --debug
          sleep 60
          kubectl get pods -A
          kubectl get svc -A

      - name: clean environment
        run: |
          helm uninstall kotal --namespace=kotal
