name: Lint and Test Charts

on:
  push:
    branches:
      - chart-lint
    tags:
      - 'v*'
    pull_request:
      branches:
        - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Add helm dependencies repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run chart-testing (lint)
        run: |
          echo 'validate-maintainers: false' > ct.yaml
          ct lint --target-branch main

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        run: |
          helm install kotal charts/kotal --create-namespace --namespace=kotal --debug
          kubectl get pods -A

      - name: clean environment
        run: |
          helm uninstall kotal --namespace=kotal
